apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
  labels:
    app: llmops
spec:
  replicas: 1 # Para produção, geralmente usamos 2 ou mais para alta disponibilidade
  selector:
    matchLabels:
      app: llmops
  template:
    metadata:
      labels:
        app: llmops
    spec:
      containers:
      - name: llmops-container
        image: llmops-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8501
        
        # --- Limites de Recursos ---
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        # --- Verificação de Saúde (Health Checks) ---
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 20

        envFrom:
          - secretRef:
              name: llmops-secrets 
---
apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  type: LoadBalancer
  selector:
    app: llmops
  ports:
    - protocol: TCP
      port: 80       # Porta externa (HTTP padrão)
      targetPort: 8501 # Porta interna do Streamlit